import React from 'react';
import { FileBarChart } from 'lucide-react';
import ManagementPageLayout from '../../components/Common/ManagementPageLayout';

const fields = [
  { key: 'reportName', label: 'Report Name', type: 'text', placeholder: 'Monthly GST Output Statement' },
  { key: 'reportType', label: 'Report Category', type: 'select', options: ['Tax & GST', 'Sales & Revenue', 'Vendor Payouts', 'Inventory Valuation', 'Event Attendance'] },
  { key: 'period', label: 'Reporting Period', type: 'text', placeholder: 'August 2026' },
  { key: 'generatedBy', label: 'Generated By', type: 'text', placeholder: 'Finance Admin' },
  { key: 'status', label: 'Status', type: 'select', options: ['ready', 'processing', 'archived'] }
];

const columns = ['reportName', 'reportType', 'period', 'generatedBy', 'status'];

export default function ReportsManagementPage() {
  return (
    <ManagementPageLayout
      pageKey="reports"
      title="Financial & Audit Reports"
      subtitle="Generate, review, and export monthly GST audit reports, sales summaries, and seller statements."
      icon={FileBarChart}
      accent="#0369a1"
      collectionName="reports"
      primaryAction="Generate Report"
      fields={fields}
      columns={columns}
      columnLabels={{
        reportName: 'Report Title',
        reportType: 'Category',
        period: 'Period',
        generatedBy: 'Generated By',
        status: 'Status'
      }}
    />
  );
}
